name: Deploy Flutter

on:
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter_version: [3.13.1]
        flutter_path: ["/opt/hostedtoolcache/flutter"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Load Flutter SDK from Cache
        uses: actions/cache@v3.2.6
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-${{ matrix.flutter_version }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ matrix.flutter_version }}

      - name: Install Packages
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href="/flutter_projection/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
